<script>

import Slider from './Slider.svelte'

export let R0 = 0;
export let D_incbation = 0;
export let D_infectious = 0;
export let CFR = 0;
export let Time_to_death = 0;

</script>

<div class="bluetitle">Transmission Variables </div>

<div style="width:100%;">

  <div>
    <div class="legendtext"><b>Basic reproduction number</b> - Average number of infections generated by one individual at epidemic’s start</div>

    <div class="rangeval" style="display:flex; justify-content: center;">
      <div style="width:58%;">
        <Slider bind:value={R0} min=0.01 max=20 step=0.01/> 
      </div>
      <div style="width:42%;">
        <div class="adjustableslidertext">
          {R0}
        </div>
      </div>
    </div>

  </div>

  <div>
    <div class="legendtext"><b>Incubation period</b> - Time between infection and symptom onset</div>

    <div class="rangeval" style="display:flex; justify-content: center;">
      <div style="width:58%;">
        <Slider type=range bind:value={D_incbation} min={0.15} max=24 step=0.0001/>
      </div>
      <div style="width:42%;">
        <div class="adjustableslidertext">
          {(D_incbation).toFixed(2)} days
        </div>
      </div>
    </div>

  </div>

  <div>
    <div class="legendtext"><b>Infectious period</b> - How long someone can spread the virus</div>

    <div class="rangeval" style="display:flex; justify-content: center;">
      <div style="width:58%;">
        <Slider bind:value={D_infectious} min={0.1} max={Time_to_death - 0.1} step=0.01/>
      </div>
      <div style="width:42%;">
        <div class="adjustableslidertext">
          {D_infectious} Days
        </div>
      </div>
    </div>

  </div>

</div>

<div class="bluetitle">Clinical Variables </div>

<div style="width:100%;">

  <div>
    <div class="legendtext"><b>Infection fatality rate</b> - Number of deaths per infection</div>

    <div class="rangeval" style="display:flex; justify-content: center;">
      <div style="width:58%;">
        <Slider bind:value={CFR} min={0} max=1 step=0.0001/>
      </div>
      <div style="width:42%;">
        <div class="adjustableslidertext">
          {(CFR*100).toFixed(2)} %
        </div>
      </div>
    </div>

  </div>

  <div>
    <div class="legendtext"><b>Time from symptom onset to death</b></div>

    <div class="rangeval" style="display:flex; justify-content: center;">
      <div style="width:58%;">
        <Slider bind:value={Time_to_death} min={(D_infectious)+0.1} max=100 step=0.01/>
      </div>
      <div style="width:42%;">
        <div class="adjustableslidertext">
          {Time_to_death} Days
        </div>
      </div>
    </div>

  </div>

</div>
