<script>

export let R0 = 0;
export let D_incbation = 0;
export let D_infectious = 0;
export let CFR = 0;
export let Time_to_death = 0;

</script>

<style>
  
  .bluetitle {
    font-weight: 300;
    font-family: Pangram,Avenir,Helvetica,sans-serif;
    margin-right: 0px;
    line-height:14px;
    font-weight: normal;
    text-align: left;
    color: rgb(71, 129, 255);
    border-bottom: 1px solid rgb(200,200,200);
    margin-bottom: 14px;
    margin-top: 20px;
    padding-bottom:5px;
    text-transform: uppercase;
    font-size: 14px
  }

  .adjustableslidertext {
    font-family: Pangram,Avenir,Helvetica,sans-serif;    
    background-color: rgb(221, 227, 243); 
    color: rgb(73, 129, 248);
    text-align: center;
    font-size: 13px;
    font-weight: bold;
    width: 85%; 
    margin-left: 10px; 
    border-radius: 10px;
  }

  .range {
    width: 100%;
    padding: 0px;
    margin: 0px;
    margin-bottom: 0px;
  }

  .legendtext{
    color:#888; 
    font-size:13px;
    padding-bottom: 6px;
    font-weight: 300;
    font-family: Pangram,Avenir,Helvetica,sans-serif;
    line-height: 15px;
  }
</style>
<div class="bluetitle">Transmission Variables </div>

<div style="width:100%;">

  <div>
    <div class="legendtext"><b>Basic reproduction number</b> - Average number of infections generated by one individual on day 0</div>

    <div style="display:flex; justify-content: center;">
      <div style="width:58%;">
        <input class="range" type=range bind:value={R0} min=0.01 max=10 step=0.01> 
      </div>
      <div style="width:42%;">
        <div class="adjustableslidertext">
          {R0}
        </div>
      </div>
    </div>

  </div>


  <div>
    <div class="legendtext"><b>Incubation period</b> - Time between infection and symptom onset</div>

    <div style="display:flex; justify-content: center;">
      <div style="width:58%;">
        <input class="range" style="margin-bottom: 8px"type=range bind:value={D_incbation} min={0.15} max=24 step=0.0001>
      </div>
      <div style="width:42%;">
        <div class="adjustableslidertext">
          {(D_incbation).toFixed(2)} days
        </div>
      </div>
    </div>

  </div>

  <div>
    <div class="legendtext"><b>Infectious period</b> - How long someone can spread the virus</div>

    <div style="display:flex; justify-content: center;">
      <div style="width:58%;">
        <input class="range" type=range bind:value={D_infectious} min={0} max=24 step=0.01>
      </div>
      <div style="width:42%;">
        <div class="adjustableslidertext">
          {D_infectious} Days
        </div>
      </div>
    </div>

  </div>

</div>

<div class="bluetitle">Clinical Variables </div>

<div style="width:100%;">

  <div>
    <div class="legendtext"><b>Infection fatality rate</b> - Number of deaths per infection</div>

    <div style="display:flex; justify-content: center;">
      <div style="width:58%;">
        <input class="range" style="margin-bottom: 8px" type=range bind:value={CFR} min={0} max=1 step=0.0001>
      </div>
      <div style="width:42%;">
        <div class="adjustableslidertext">
          {(CFR*100).toFixed(2)} %
        </div>
      </div>
    </div>

  </div>

  <div>
    <div class="legendtext"><b>Time from symptom onset to death</b></div>

    <div style="display:flex; justify-content: center;">
      <div style="width:58%;">
        <input class="range" type=range bind:value={Time_to_death} min={(D_infectious)+0.1} max=100 step=0.01>
      </div>
      <div style="width:42%;">
        <div class="adjustableslidertext">
          {Time_to_death} Days
        </div>
      </div>
    </div>

  </div>

</div>
